Repository thePlums/web-app, pull requests merged in 2018-03, with the labels that each got.

#65 Added header with logo and log out button
  css/header.css
  images/logo.svg
  index.html
Labels: content, dev

#66 Rounded corners of cards
  css/main.css
Labels: dev

#64 Created new notes page, added icons
  note-icons/Bold.svg
  note-icons/Center.svg
  note-icons/Colour.svg
  note-icons/Down.svg
  note-icons/Italic.svg
  note-icons/Justify.svg
  note-icons/Left.svg
  note-icons/Right.svg
  note-icons/Underline.svg
  pages/notes.html
Labels: dev

#67 replace FAB add icon
  icons/fab-add.svg
Labels: design, product

#71 added images to video-collection page
  css/main.css
  images/video1.png
  images/video2.png
  images/video3.png
  pages/video-collection.html
Labels: dev

#69 Added side-nav and fixed things
  css/header.css
  css/left-nav.css
  css/main.css
  css/modules.css
  icons/audio.svg
  icons/calendar.svg
  icons/camera.svg
  icons/fab-add.svg
  icons/fab-audio.svg
  icons/fab-notes.svg
  icons/fab-palettes.svg
  icons/fab-photo.svg
  icons/fab-video.svg
  icons/folder.svg
  icons/home.svg
  icons/icons.svg
  icons/note.svg
  icons/palette.svg
  icons/palette2.svg
  icons/pause.svg
  icons/play.svg
  icons/reminder.svg
  icons/replay.svg
  icons/settings.svg
  icons/share.svg
  icons/stop.svg
  icons/video.svg
  index.html
  left-nav.html
Labels: design, dev

#73 add fab icon back
  icons/fab-add.svg
Labels: content, design

#72 changing main css back to normal.
  css/main.css
Labels: dev

#70 Added images to audio-collection page
  .gitignore
  css/audio-collection.css
  css/main.css
  images/audio1.png
  images/audio2.png
  pages/audio-collection.html
Labels: dev

#75 Audio html
  audio-icons/dragdrop.svg
  audio-icons/play-btn.svg
  audio-icons/record-btn.svg
  audio-icons/soundwave.svg
  css/audio.css
  pages/audio.html
Labels: design, dev, product

#76 linking pages on left side nav
  index.html
Labels: dev

#80 Hamburger button
  css/hamburger-button.css
  hamburger-button.html
Labels: dev

#81 added nav to notes page
  pages/notes.html
Labels: dev

#82 added palettes page!
  css/audio.css
  css/main.css
  pages/audio.html
  pages/palettes.html
Labels: content, dev

#83 Link fab nav
  css/audio.css
  index.html
  pages/audio.html
Labels: dev

#85 Audio html
  css/audio.css
  pages/audio.html
  pages/notes.html
Labels: dev

#87 add linked fab nav to all pages
  pages/audio-collection.html
  pages/audio.html
  pages/note-collection.html
  pages/notes.html
  pages/palette-collection.html
  pages/palettes.html
  pages/photo-collection.html
  pages/video-collection.html
Labels: dev

#88 link fab nav on home
  index.html
  pages/palettes.html
Labels: dev

#90 fixed the small nav in palette
  css/main.css
  pages/palettes.html
Labels: bug, content

#89 add current class to side navs on all pages
  css/left-nav.css
  index.html
  pages/audio-collection.html
  pages/audio.html
  pages/note-collection.html
  pages/palette-collection.html
  pages/palettes.html
  pages/photo-collection.html
  pages/video-collection.html
Labels: design, dev

#91 audio info gutter
  pages/audio.html
Labels: dev

#93 fixed hovers
  pages/notes.html
Labels: design

#92 fixed all hamburger button issues
  css/audio-collection.css
  css/hamburger-button.css
  css/header.css
  css/main.css
  css/note-collection.css
  css/palette-collection.css
  css/photo-collection.css
  css/video-collection.css
  index.html
  pages/audio-collection.html
  pages/audio.html
  pages/note-collection.html
  pages/notes.html
  pages/palette-collection.html
  pages/palettes.html
  pages/photo-collection.html
  pages/video-collection.html
Labels: dev

#94 fixed links on cards
  index.html
  pages/audio-collection.html
  pages/note-collection.html
  pages/palette-collection.html
  pages/photo-collection.html
  pages/video-collection.html
Labels: dev

#95 Photo and video pages
  pages/photo.html
  pages/video.html
Labels: content

#97 changed colour
  css/hamburger-button.css
Labels: design

#99 Changed Titles
  index.html
  pages/audio-collection.html
  pages/audio.html
  pages/notes.html
  pages/palette-collection.html
  pages/palettes.html
  pages/photo-collection.html
  pages/photo.html
  pages/video-collection.html
  pages/video.html
Labels: enhancement

#100 add fac icon
  icons/fav-icon.png
  index.html
Labels: design, dev, product

#102 add fav ../
  pages/audio-collection.html
  pages/audio.html
  pages/note-collection.html
  pages/notes.html
  pages/palette-collection.html
  pages/palettes.html
  pages/photo-collection.html
  pages/photo.html
  pages/video-collection.html
  pages/video.html
Labels: design, dev

#103 added more cards in main page
  index.html
Labels: content

#107 fix nav icon hover
  css/left-nav.css
Labels: design, product

#109 Added auto-save and emojis
  css/notes.css
  pages/notes.html
  pages/palettes.html
  pages/photo.html
  pages/video.html
Labels: design, enhancement

#111 Add Alt tags and Aria-labels to all pages
  index.html
  pages/audio-collection.html
  pages/audio.html
  pages/note-collection.html
  pages/palette-collection.html
  pages/palettes.html
  pages/photo-collection.html
  pages/photo.html
  pages/video-collection.html
  pages/video.html
Labels: content, dev, enhancement
