Repository thePlums/web-app, pull requests merged in 2018-02, with the labels that each got.

#26 Added basic headings
  index.html
Labels: bug, dev

#28 katrina's fake branch and h2
  index.html
Labels: dev

#29 Project Manager H2
  index.html
Labels: dev

#38 html for cards
  index.html
Labels: dev

#41 Indentation fix css links
  index.html
Labels: content, product

#36 created type.css
  css/type.css
Labels: dev

#34 created main.css with basic code setup
  css/main.css
Labels: dev

#43 added images
  images/bike.png
  images/butterfly-art.png
  images/colour-palette.png
  images/drawing-note.png
  images/flower.png
  images/quotes-note.png
  images/record-audio.png
  images/skateboard-video.png
Labels: dev

#44 Added units
  index.html
Labels: bug

#45 adding new icons
  icons/audio.svg
  icons/calendar.svg
  icons/camera.svg
  icons/folder.svg
  icons/home.svg
  icons/note.svg
  icons/palette.svg
  icons/pause.svg
  icons/play.svg
  icons/reminder.svg
  icons/replay.svg
  icons/settings.svg
  icons/share.svg
  icons/stop.svg
  icons/video.svg
Labels: dev

#46 add specifice class name to container class
  css/nav-fab.css
  index.html
Labels: dev

#47 created specific class name for card icons
  index.html
Labels: dev

#48 changed class in css
  css/main.css
Labels: dev

#49 Fixing fab icon
  css/nav-fab.css
  index.html
Labels: dev

#53 Made it responsive
  css/main.css
  index.html
Labels: design, enhancement

#54 fixed
  css/main.css
Labels: enhancement

#57 Fixed the padding on the cards
  index.html
Labels: enhancement

#58 Fab icons, specific
  icons/fab-add.svg
  icons/fab-audio.svg
  icons/fab-icon.svg
  icons/fab-notes.svg
  icons/fab-palettes.svg
  icons/fab-photo.svg
  icons/fab-video.svg
  index.html
Labels: content, design, dev

#56 changed card icon colour
  css/main.css
  icons/folder.svg
  icons/palette.svg
  icons/reminder.svg
  icons/share.svg
  index.html
Labels: design
